version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # or any you actually need
    commands:
      - echo Installing dependencies...
      - pip install --upgrade awscli jq
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - |
        aws sts assume-role \
          --role-arn $ACCOUNT1_ROLE_ARN \
          --role-session-name ecrsession > assume-role-output.txt

      - export AWS_ACCESS_KEY_ID=$(cat assume-role-output.txt | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(cat assume-role-output.txt | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(cat assume-role-output.txt | jq -r '.Credentials.SessionToken')

      - echo Logging in to target ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ACCOUNT1_ECR_REPO_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t vamshi-microservice .
      - docker tag vamshi-microservice:latest $ACCOUNT1_ECR_REPO_URI:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $ACCOUNT1_ECR_REPO_URI:latest
