version: 0.2

env:
  variables:
    ECR_STACK_NAME: vamshi-ecr-stack
    ECS_STACK_NAME: vamshi-ecs-stack
    ACCOUNT1_ROLE_ARN: arn:aws:iam::044854092841:role/CrossAccountECRDeploymentRole

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install --upgrade awscli jq

  build:
    commands:
      - echo "Assuming role in Account 1..."
      - >
        aws sts assume-role \
          --role-arn "$ACCOUNT1_ROLE_ARN" \
          --role-session-name ecrDeploySession > temp_creds.json
      - export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId temp_creds.json)
      - export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey temp_creds.json)
      - export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken temp_creds.json)

      - echo "Deploying ECR stack in Account 1..."
      - aws cloudformation deploy \
          --template-file infra/ecr.yaml \
          --stack-name $ECR_STACK_NAME \
          --capabilities CAPABILITY_NAMED_IAM

      - echo "Switching back to Account 2..."
      - unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN

      - echo "Deploying ECS infrastructure in Account 2..."
      - aws cloudformation deploy \
          --template-file infra/ecs_infra.yaml \
          --stack-name $ECS_STACK_NAME \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides EcrImageUri=dummy.dkr.ecr.us-east-1.amazonaws.com/placeholder:latest
