version: 0.2

env:
  variables:
    ACCOUNT1_ROLE_ARN: arn:aws:iam::044854092841:role/CrossAccountECRPushRole
    ACCOUNT1_ECR_REPO_URI: 044854092841.dkr.ecr.us-east-1.amazonaws.com/vamshi-microservice

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli jq

  pre_build:
    commands:
      - echo "Assuming role into Account 1..."
      - aws sts assume-role \
          --role-arn "$ACCOUNT1_ROLE_ARN" \
          --role-session-name ecrsession > assume-role-output.txt
      - export AWS_ACCESS_KEY_ID=$(cat assume-role-output.txt | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(cat assume-role-output.txt | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(cat assume-role-output.txt | jq -r '.Credentials.SessionToken')
      - echo "Logging into target ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ACCOUNT1_ECR_REPO_URI

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Docker image..."
      - cd microservice-app
      - docker build -t vamshi-microservice .
      - docker tag vamshi-microservice:latest $ACCOUNT1_ECR_REPO_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ACCOUNT1_ECR_REPO_URI:latest
      - echo "✅ Build and push complete on $(date)"

artifacts:
  files:
    - '**/*'
