version: 0.2

env:
  variables:
    PUBLIC_ECR_ALIAS: vamshi123                # Must be lowercase
    PUBLIC_REPO_NAME: microservice-app         # Must be lowercase
    IMAGE_TAG: latest

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli jq
      - echo "✔️ Dependencies installed"

  pre_build:
    commands:
      - echo "No login needed for public ECR if permissions are correct"
      - export IMAGE_URI="public.ecr.aws/${PUBLIC_ECR_ALIAS}/${PUBLIC_REPO_NAME}:${IMAGE_TAG}"
      - echo "IMAGE_URI is $IMAGE_URI"

  build:
    commands:
      - echo "Build started on `date`"
      - cd microservice-app
      - echo "Building the Docker image..."
      - docker build -t $PUBLIC_REPO_NAME:$IMAGE_TAG .
      - docker tag $PUBLIC_REPO_NAME:$IMAGE_TAG $IMAGE_URI

  post_build:
    commands:
      - echo "Pushing the Docker image to public ECR..."
      - docker push $IMAGE_URI
      - echo "✔️ Image pushed to public ECR: $IMAGE_URI"

artifacts:
  files:
    - '**/*'
