version: 0.2

env:
  variables:
    ACCOUNT1_ROLE_ARN: arn:aws:iam::044854092841:role/CrossAccountECRDeploymentRole
    ECR_REPO_NAME: vamshi-cross-ecr
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing jq and AWS CLI..."
      - pip install --upgrade awscli jq

  pre_build:
    commands:
      - echo "Assuming role into Account 1 to get ECR credentials..."
      - aws sts assume-role --role-arn "$ACCOUNT1_ROLE_ARN" --role-session-name ecrPushSession > temp_creds.json
      - export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId temp_creds.json)
      - export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey temp_creds.json)
      - export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken temp_creds.json)
      - ACCOUNT1_ID=$(echo "$ACCOUNT1_ROLE_ARN" | cut -d':' -f5)
      - ECR_URI="$ACCOUNT1_ID.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPO_NAME"

      - echo "Logging in to Account 1 ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin "$ECR_URI"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t "$ECR_REPO_NAME:$IMAGE_TAG" .
      - docker tag "$ECR_REPO_NAME:$IMAGE_TAG" "$ECR_URI:$IMAGE_TAG"

  post_build:
    commands:
      - echo "Pushing Docker image to Account 1 ECR..."
      - docker push "$ECR_URI:$IMAGE_TAG"

artifacts:
  files:
    - '**/*'
