version: 0.2

env:
  variables:
    PUBLIC_ECR_ALIAS: "t3e3b1o4"
    PUBLIC_REPO_NAME: "vamshi-microservice"
    IMAGE_TAG: "latest"
    IMAGE_URI: "public.ecr.aws/${PUBLIC_ECR_ALIAS}/${PUBLIC_REPO_NAME}:${IMAGE_TAG}"
    STACK_NAME: vamshi-ecs-infra

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Preparing to deploy ECS infrastructure using CloudFormation..."

  build:
    commands:
      - echo "Deploying ECS infrastructure to Account 2 using CloudFormation..."
      - |
        aws cloudformation deploy \
          --template-file infra/account2/ecs_infra.yaml \
          --stack-name $STACK_NAME \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides EcrImageUri=$IMAGE_URI

artifacts:
  files:
    - '**/*'
