version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"
    PUBLIC_ECR_ALIAS: "t3e3b1o4"
    PUBLIC_REPO_NAME: "vamshi-microservice"
    IMAGE_URI: "public.ecr.aws/${PUBLIC_ECR_ALIAS}/${PUBLIC_REPO_NAME}:${IMAGE_TAG}"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli jq
      - echo "✔️ Dependencies installed"

  pre_build:
    commands:
      - echo "No login needed for public ECR if permissions are correct"
      - echo "IMAGE_URI is $IMAGE_URI"

  build:
    commands:
      - echo "Build started on `date`"
      - cd microservice-app
      - echo "Building the Docker image..."
      - docker build -t $PUBLIC_REPO_NAME:$IMAGE_TAG .
      - docker tag $PUBLIC_REPO_NAME:$IMAGE_TAG $IMAGE_URI
      - echo "✔️ Docker image built and tagged as $IMAGE_URI"

  post_build:
    commands:
      - echo "Pushing the Docker image to public ECR..."
      - docker push $IMAGE_URI
      - echo "✔️ Docker image pushed successfully"
      - echo "Build completed on `date`"
