AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild Projects for Multi-Account ECS Deployment Pipeline

Resources:

  AppBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: vamshi-app-build
      Source:
        Type: CODEPIPELINE
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ACCOUNT1_ROLE_ARN
            Value: arn:aws:iam::044854092841:role/CrossAccountECRPushRole
          - Name: ACCOUNT1_ECR_REPO_URI
            Value: 044854092841.dkr.ecr.us-east-1.amazonaws.com/vamshi-microservice
      ServiceRole: arn:aws:iam::992313771121:role/CodeBuildServiceRole
      TimeoutInMinutes: 10

  InfraBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: vamshi-infra-build
      Source:
        Type: CODEPIPELINE
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      ServiceRole: arn:aws:iam::992313771121:role/CodeBuildServiceRole
      TimeoutInMinutes: 10

  ECSDeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: vamshi-ecs-deploy
      Source:
        Type: CODEPIPELINE
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ACCOUNT1_ROLE_ARN
            Value: arn:aws:iam::044854092841:role/CrossAccountECRPushRole
          - Name: ACCOUNT1_ECR_REPO_URI
            Value: 044854092841.dkr.ecr.us-east-1.amazonaws.com/vamshi-microservice
          - Name: ECS_CLUSTER_NAME
            Value: vamshi-cluster
          - Name: ECS_SERVICE_NAME
            Value: vamshi-service
      ServiceRole: arn:aws:iam::992313771121:role/CodeBuildServiceRole
      TimeoutInMinutes: 10

