AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild projects for Infra and App in multi-account setup

Resources:

  InfraBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: vamshi-infra-build
      Description: Builds and deploys ECR infra stack in Account 1
      ServiceRole: arn:aws:iam::992313771121:role/vamshi-codebuild-role
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-infra.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: ACCOUNT1_ROLE_ARN
            Value: arn:aws:iam::044854092841:role/CrossAccountECRDeploymentRole
          - Name: ECR_STACK_NAME
            Value: vamshi-ecr-stack

  AppBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: vamshi-app-build
      Description: Builds and pushes Docker image to ECR in Account 1
      ServiceRole: arn:aws:iam::992313771121:role/vamshi-codebuild-role
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-app.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: ACCOUNT1_ROLE_ARN
            Value: arn:aws:iam::044854092841:role/CrossAccountPushRole
          - Name: ACCOUNT1_ECR_REPO_URI
            Value: 044854092841.dkr.ecr.us-east-1.amazonaws.com/vamshi-microservice
