AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild Projects for Infra and App Deployment

Parameters:
  GitHubRepoName:
    Type: String
    Default: multi-account-ecs-cicd
  GitHubOwner:
    Type: String
    Default: vamshik2506
  GitHubBranch:
    Type: String
    Default: main
  GitHubOAuthToken:
    Type: String
    NoEcho: true

Resources:

  InfraBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: vamshi-infra-build
      Source:
        Type: GITHUB
        Location: !Sub "https://github.com/${GitHubOwner}/${GitHubRepoName}.git"
        BuildSpec: buildspec-infra.yml
        GitCloneDepth: 1
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn

  AppBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: vamshi-app-build
      Source:
        Type: GITHUB
        Location: !Sub "https://github.com/${GitHubOwner}/${GitHubRepoName}.git"
        BuildSpec: buildspec-app.yml
        GitCloneDepth: 1
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: vamshi-codebuild-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "*"
                Resource: "*"
