AWSTemplateFormatVersion: '2010-09-09'
Description: Multi-account CI/CD with Infra and App Deploy

Parameters:
  GitHubRepo:
    Type: String
  GitHubBranch:
    Type: String
    Default: main
  GitHubOwner:
    Type: String
  GitHubOAuthToken:
    Type: String
    NoEcho: true

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "vamshi-artifacts-${AWS::AccountId}"

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: vamshi-pipeline-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: vamshi-cicd-pipeline
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubOAuthToken
              RunOrder: 1

        - Name: DeployInfra
          Actions:
            - Name: InfraBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: InfraBuildOutput
              Configuration:
                ProjectName: vamshi-infra-build
              RunOrder: 1

        - Name: BuildAndDeployApp
          Actions:
            - Name: AppBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: vamshi-app-build
              RunOrder: 1
