AWSTemplateFormatVersion: '2010-09-09'
Description: Multi-Account ECS Deployment Pipeline

Resources:

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: vamshi-ecs-cicd-pipeline
      RoleArn: arn:aws:iam::992313771121:role/CodePipelineServiceRole
      ArtifactStore:
        Type: S3
        Location: vamshi-codepipeline-artifacts
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: vam-kri
                Repo: multi-account-ecs-cicd
                Branch: main
                OAuthToken: "{{resolve:secretsmanager:GitHubToken:SecretString:token}}"
              RunOrder: 1

        - Name: InfraDeploy
          Actions:
            - Name: InfraBuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: vamshi-infra-build
              RunOrder: 1

        - Name: AppBuild
          Actions:
            - Name: AppBuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: AppBuildOutput
              Configuration:
                ProjectName: vamshi-app-build
              RunOrder: 1

        - Name: ECSInfra
          Actions:
            - Name: ECSInfraAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: vamshi-ecs-infra
              RunOrder: 1

        - Name: ECSDeploy
          Actions:
            - Name: ECSDeployAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: vamshi-ecs-deploy
              RunOrder: 1

