AWSTemplateFormatVersion: '2010-09-09'
Description: Create Public ECR Repository

Resources:
  PublicECRRepository:
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: vamshi-microservice
      RepositoryCatalogData:
        RepositoryDescription: "Public microservice image repository for multi-account ECS"
      Tags:
        - Key: Name
          Value: vamshi-microservice

Outputs:
  PublicECRRepositoryUri:
    Description: URI of the public ECR repository
    Value: !Sub "public.ecr.aws/${AWS::AccountId}/vamshi-microservice"
